[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dkim_key_oracle = "FXo8XW4G5qTzR9G4EnRcQGDBwJ2EciWfni57gV2pLL7w"
smart_account_solana = "8CfU477AfpF2ttCoxiF7s9Tdbmsvh9A8NauonsUGujuU"
upgrade_mock = "tqVoUexaDpW35SukukXhMXhtWC1n1PBJq8riiiBZf8R"
vault = "A7CsUmonBupSwmfAwzavwTnPEZbqfryWG8qSfkFmUMwB"
zk_email_verifier = "5ZWpsrh3afwUcbuiX6m1LwCriFFqtKnTf8DkJjvUfYb9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/pay.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
faucet_port = 1337
faucet_sol = "1337"
ledger = ".anchor/test-ledger"
rpc_port = 8899
